#!/usr/bin/env bash
set -Eeuo pipefail

cosmic-wm start sysadmin-ws1 --timeout 90
cosmic-wm start sysadmin-ws2 --timeout 90
cosmic-wm start sysadmin-ws3 --timeout 90
cosmic-wm start sysadmin-ws4 --timeout 90
cosmic-wm start sysadmin-ws5 --timeout 90
cosmic-wm start sysadmin-ws6 --timeout 90
